// Types generated by Supabase CLI
// Run: supabase gen types typescript --project-id your-project > lib/supabase/types.ts

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: number
          supabase_user_id: string
          has_access: boolean
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          supabase_user_id: string
          has_access?: boolean
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          supabase_user_id?: string
          has_access?: boolean
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      purchases: {
        Row: {
          id: number
          user_id: number
          stripe_payment_intent_id: string | null
          stripe_session_id: string | null
          amount: number
          currency: string
          status: string
          product_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          user_id: number
          stripe_payment_intent_id?: string | null
          stripe_session_id?: string | null
          amount: number
          currency?: string
          status?: string
          product_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          user_id?: number
          stripe_payment_intent_id?: string | null
          stripe_session_id?: string | null
          amount?: number
          currency?: string
          status?: string
          product_name?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types for easier usage
export type User = Database['public']['Tables']['users']['Row']
export type Purchase = Database['public']['Tables']['purchases']['Row']
export type NewUser = Database['public']['Tables']['users']['Insert']
export type NewPurchase = Database['public']['Tables']['purchases']['Insert'] 